language: perl
perl:
    - "5.22"
    - "5.24"
before_install:
    #      cpanm -n Devel::Cover::Report::Kritika
    - cpanm -n https://github.com/kritikaio/devel-cover-report-kritika-perl/archive/master.tar.gz
install:
    - cpanm -n -q --skip-satisfied --installdeps .
script:
    - perl Build.PL && ./Build build && cover -test -report kritika
